---
output: html_document
---

## Excercise 8.8

__In the lab, a classification tree was applied to the Carseats data set after converting Sales into a qualitative response variable. Now we will seek to predict Sales using regression trees and related approaches, treating the response as a quantitative variable.__

a. __Split the data set into a training set and a test set.__

<!-- enter your solution here -->

b. __Fit a regression tree to the training set. Plot the tree, and interpret the results. What test MSE do you obtain?__

<!-- enter your solution here -->

c. __Use cross-validation in order to determine the optimal level of tree complexity. Does pruning the tree improve the test MSE?__

<!-- enter your solution here -->

d. __Use the bagging approach in order to analyze this data. What test MSE do you obtain? Use the `importance()` function to determine which variables are most important.__

<!-- enter your solution here -->

e. __Use random forests to analyze this data. What test MSE do you obtain? Use the `importance()` function to determine which variables are most important. Describe the effect of m, the number of variables considered at each split, on the error rate obtained__

<!-- enter your solution here -->
