---
output: html_document
---

## Excercise 8.9

__This problem involves the “OJ” data set which is part of the “ISLR” package.__

a. __Create a training set containing a random sample of 800 observations, and a test set containing the remaining observations.__

<!-- enter your solution here -->

b. __Fit a tree to the training data, with “Purchase” as the response and the other variables except for “Buy” as predictors. Use the “summary()” function to produce summary statistics about the tree, and describe the results obtained. What is the training error rate? How many terminal nodes does the tree have?__

<!-- enter your solution here -->

c. __Type in the name of the tree object in order to get a detailed text output. Pick one of the terminal nodes, and interpret the information displayed.__

<!-- enter your solution here -->

d. __Create a plot of the tree, and interpret the results.__

<!-- enter your solution here -->

e. __Predict the response on the test data, and produce a confusion matrix comparing the test labels to the predicted test labels. What is the test error rate?__

<!-- enter your solution here -->

f. __Apply the “cv.tree()” function to the training set in order to determine the optimal size tree.__

<!-- enter your solution here -->

g. __Produce a plot with tree size on the x-axis and cross-validated classification error rate on the y-axis.__

<!-- enter your solution here -->

h. __Which tree size corresponds to the lowest cross-validated classification error rate?__

<!-- enter your solution here -->

i. __Produce a pruned tree corresponding to the optimal tree size obtained using cross-validation. If cross-validation does not lead to selection of a pruned tree, then create a pruned tree with five terminal nodes.__

<!-- enter your solution here -->

j. __Compare the training error rates between the pruned and unpruned trees. Which is higher?__

<!-- enter your solution here -->

k. __Compare the test error rates between the pruned and unpruned trees. Which is higher?__

<!-- enter your solution here -->
